# Warning: This file is automatically generated. It will be overwritten.
# Stage: dev

# COGNITO
#USER_POOL_ID = "eu-west-1_iV3vGbOYP"
#ADMIN_GROUP_NAME = "admin"
#PRO_GROUP_NAME = 'pro'
#PREMIUM_GROUP_NAME = 'premium'
#BASIC_GROUP_NAME = 'basic'
#NOPLAN_GROUP_NAME = 'noPlan'

# APPSYNC
#API_URL = "https://ros64oqufncqpavrzukwbp6gb4.appsync-api.eu-west-1.amazonaws.com/graphql"
#API_KEY = "da2-qusxcftz7vfhdkktdtvh54waam"
#API_HEADERS = {"x-api-key": API_KEY}

# Warning: This file is automatically generated. It will be overwritten.
# Stage: staging

# COGNITO
USER_POOL_ID = "eu-west-1_JRepGPrY3"
ADMIN_GROUP_NAME = "admin"
PRO_GROUP_NAME = 'pro'
PREMIUM_GROUP_NAME = 'premium'
BASIC_GROUP_NAME = 'basic'
NOPLAN_GROUP_NAME = 'noPlan'

# APPSYNC
API_URL = "https://5ww6klfsirbwrjrssk6nyhfyhi.appsync-api.eu-west-1.amazonaws.com/graphql"
API_KEY = "da2-4ll5atm5xjfdzl75ibhm52paym"
API_HEADERS = {"x-api-key": API_KEY}

